systemPrompt:
  contributors:
    - id: main-prompt
      type: static
      priority: 100
      content: |
        You are a helpful AI assistant running via Dexto's REST API server.
        You have access to:
        - Local filesystem storage and SQLite database
        - Custom text utilities tools (count_words, transform_case, reverse_text)

        When asked to analyze or manipulate text, use your built-in text utility tools.
        You're accessible via HTTP at http://localhost:3000

llm:
  provider: openai
  model: gpt-4o-mini
  apiKey: $OPENAI_API_KEY

# Enable the custom text-utils tool that's bundled in the image
customTools:
  - type: text-utils
    maxLength: 10000

# Note: Storage config not specified - will use image defaults:
# - blob: local filesystem (./data/blobs)
# - database: sqlite (./data/agent.db)
# - cache: in-memory
