/**
 * Process Service Error Codes
 *
 * Standardized error codes for process execution and management
 */

export enum ProcessErrorCode {
    // Command validation errors
    INVALID_COMMAND = 'PROCESS_INVALID_COMMAND',
    COMMAND_BLOCKED = 'PROCESS_COMMAND_BLOCKED',
    COMMAND_TOO_LONG = 'PROCESS_COMMAND_TOO_LONG',
    INJECTION_DETECTED = 'PROCESS_INJECTION_DETECTED',
    APPROVAL_REQUIRED = 'PROCESS_APPROVAL_REQUIRED',
    APPROVAL_DENIED = 'PROCESS_APPROVAL_DENIED',

    // Execution errors
    EXECUTION_FAILED = 'PROCESS_EXECUTION_FAILED',
    TIMEOUT = 'PROCESS_TIMEOUT',
    PERMISSION_DENIED = 'PROCESS_PERMISSION_DENIED',
    COMMAND_NOT_FOUND = 'PROCESS_COMMAND_NOT_FOUND',
    WORKING_DIRECTORY_INVALID = 'PROCESS_WORKING_DIRECTORY_INVALID',

    // Process management errors
    PROCESS_NOT_FOUND = 'PROCESS_NOT_FOUND',
    TOO_MANY_PROCESSES = 'PROCESS_TOO_MANY_PROCESSES',
    KILL_FAILED = 'PROCESS_KILL_FAILED',
    OUTPUT_BUFFER_FULL = 'PROCESS_OUTPUT_BUFFER_FULL',

    // Configuration errors
    INVALID_CONFIG = 'PROCESS_INVALID_CONFIG',
    SERVICE_NOT_INITIALIZED = 'PROCESS_SERVICE_NOT_INITIALIZED',
}
