# Image: Specifies the provider bundle for this agent
image: '@dexto/image-local'

systemPrompt:
  contributors:
    - id: main-prompt
      type: static
      priority: 100
      content: |
        You are a helpful AI assistant running on Dexto's local base image.
        You have access to:
        - Filesystem tools (read, write, edit, glob, grep files)
        - Process tools (bash execution, output reading)

        When asked to work with files or run commands, use your built-in tools.

llm:
  provider: openai
  model: gpt-4o-mini
  apiKey: $OPENAI_API_KEY

# Enable filesystem and process tools from the image
customTools:
  - type: filesystem-tools
    allowedPaths: ['.']
    blockedPaths: ['.git', 'node_modules']
  - type: process-tools
    securityLevel: moderate

# Note: Storage config not specified - will use image defaults:
# - blob: local filesystem (./data/blobs)
# - database: sqlite (./data/agent.db)
# - cache: in-memory
