/**
 * Error codes for memory operations
 */
export enum MemoryErrorCode {
    // General errors
    MEMORY_NOT_FOUND = 'MEMORY_NOT_FOUND',
    MEMORY_ALREADY_EXISTS = 'MEMORY_ALREADY_EXISTS',

    // Validation errors
    MEMORY_CONTENT_REQUIRED = 'MEMORY_CONTENT_REQUIRED',
    MEMORY_CONTENT_TOO_LONG = 'MEMORY_CONTENT_TOO_LONG',
    MEMORY_INVALID_ID = 'MEMORY_INVALID_ID',
    MEMORY_INVALID_TAGS = 'MEMORY_INVALID_TAGS',

    // Storage errors
    MEMORY_STORAGE_ERROR = 'MEMORY_STORAGE_ERROR',
    MEMORY_RETRIEVAL_ERROR = 'MEMORY_RETRIEVAL_ERROR',
    MEMORY_DELETE_ERROR = 'MEMORY_DELETE_ERROR',
}
