import type { LLMRouter, LLMProvider } from '../llm/types.js';

/**
 * Internal representation of a message in a conversation.
 * Standardizes message format across different LLM providers.
 */
export interface ImageData {
    image: string | Uint8Array | Buffer | ArrayBuffer | URL;
    mimeType?: string;
}

export interface FileData {
    data: string | Uint8Array | Buffer | ArrayBuffer | URL;
    mimeType: string;
    filename?: string;
}

export interface TextPart {
    type: 'text';
    text: string;
}

export interface ImagePart extends ImageData {
    type: 'image';
}

export interface FilePart extends FileData {
    type: 'file';
}

export interface SanitizedToolResult {
    /** Ordered content parts ready for rendering or provider formatting */
    content: Array<TextPart | ImagePart | FilePart>;
    /**
     * Resource references created during sanitization (e.g. blob store URIs).
     * Consumers can dereference these via ResourceManager APIs.
     */
    resources?: Array<{
        uri: string;
        kind: 'image' | 'audio' | 'video' | 'binary';
        mimeType: string;
        filename?: string;
    }>;
    meta: {
        toolName: string;
        toolCallId: string;
        success?: boolean;
    };
}

/**
 * Token usage accounting for LLM responses
 */
export interface TokenUsage {
    inputTokens?: number;
    outputTokens?: number;
    reasoningTokens?: number;
    totalTokens?: number;
}

/**
 * Tool approval tracking metadata
 */
export interface ApprovalMetadata {
    /** Whether this tool call required user approval before execution */
    requireApproval?: boolean;
    /** The approval status (only present if requireApproval is true) */
    approvalStatus?: 'pending' | 'approved' | 'rejected';
}

/**
 * LLM execution metadata
 */
export interface LLMMetadata {
    /** Model identifier for assistant messages */
    model?: string;
    /** Provider identifier for assistant messages */
    provider?: LLMProvider;
    /** Router metadata for assistant messages */
    router?: LLMRouter;
}

/**
 * Extensible metadata for messages.
 * Allows adding new features without modifying the core InternalMessage type.
 */
export interface MessageMetadata extends ApprovalMetadata, LLMMetadata {
    /** Token usage accounting for this assistant response */
    tokenUsage?: TokenUsage;

    /** Model reasoning text associated with an assistant response */
    reasoning?: string;

    // Future extensibility: branching, editing, versioning, etc.
    /** Parent message ID for branching/threading */
    parentMessageId?: string;
    /** Edit timestamp if message was edited */
    editedAt?: number;
    /** Branch ID for conversation branching */
    branchId?: string;

    /** Allow custom metadata fields for future extensions */
    [key: string]: unknown;
}

export interface InternalMessage {
    /**
     * Unique message identifier (UUID).
     * Auto-generated by ContextManager.addMessage() if not provided.
     */
    id?: string;

    /**
     * The role of the entity sending the message.
     * - 'system': System instructions or context
     * - 'user': End-user input
     * - 'assistant': LLM response
     * - 'tool': Result from a tool execution
     */
    role: 'system' | 'user' | 'assistant' | 'tool';

    /**
     * Timestamp when the message was created (Unix timestamp in milliseconds).
     * Auto-generated by ContextManager.addMessage() if not provided.
     */
    timestamp?: number;

    /**
     * The content of the message.
     * - String for system, assistant (text only), and tool messages.
     * - Array of parts for user messages (can include text, images, and files).
     * - null if an assistant message only contains tool calls.
     */
    content: string | null | Array<TextPart | ImagePart | FilePart>;

    /**
     * Tool calls made by the assistant.
     * Only present in assistant messages when the LLM requests tool execution.
     */
    toolCalls?: Array<{
        /**
         * Unique identifier for this tool call
         */
        id: string;

        /**
         * The type of tool call (currently only 'function' is supported)
         */
        type: 'function';

        /**
         * Function call details
         */
        function: {
            /**
             * Name of the function to call
             */
            name: string;

            /**
             * Arguments for the function in JSON string format
             */
            arguments: string;
        };
    }>;

    /**
     * ID of the tool call this message is responding to.
     * Only present in tool messages.
     */
    toolCallId?: string;

    /**
     * Name of the tool that produced this result.
     * Only present in tool messages.
     */
    name?: string;

    /**
     * Extensible metadata for the message.
     * Contains approval tracking, LLM metadata, token usage, and custom fields.
     *
     * This field enables adding new features without modifying the core type.
     * New metadata should be added here instead of as top-level fields.
     */
    metadata?: MessageMetadata;
}
