import type { LLMProvider } from '../llm/types.js';

/**
 * Internal representation of a message in a conversation.
 * Standardizes message format across different LLM providers.
 */
export interface ImageData {
    image: string | Uint8Array | Buffer | ArrayBuffer | URL;
    mimeType?: string;
}

export interface FileData {
    data: string | Uint8Array | Buffer | ArrayBuffer | URL;
    mimeType: string;
    filename?: string;
}

export interface TextPart {
    type: 'text';
    text: string;
}

export interface ImagePart extends ImageData {
    type: 'image';
}

export interface FilePart extends FileData {
    type: 'file';
}

/**
 * UI Resource content part for MCP-UI interactive components.
 * Enables MCP servers to return rich, interactive UI (live streams, dashboards, forms).
 * @see https://mcpui.dev/ for MCP-UI specification
 */
export interface UIResourcePart {
    type: 'ui-resource';
    /** URI identifying the UI resource, must start with ui:// */
    uri: string;
    /** MIME type: text/html, text/uri-list, or application/vnd.mcp-ui.remote-dom */
    mimeType: string;
    /** Inline HTML content or URL (for text/html and text/uri-list) */
    content?: string;
    /** Base64-encoded content (alternative to content field) */
    blob?: string;
    /** Optional metadata for the UI resource */
    metadata?: {
        /** Display title for the UI resource */
        title?: string;
        /** Preferred rendering size in pixels */
        preferredSize?: { width: number; height: number };
    };
}

export interface SanitizedToolResult {
    /** Ordered content parts ready for rendering or provider formatting */
    content: Array<TextPart | ImagePart | FilePart | UIResourcePart>;
    /**
     * Resource references created during sanitization (e.g. blob store URIs).
     * Consumers can dereference these via ResourceManager APIs.
     */
    resources?: Array<{
        uri: string;
        kind: 'image' | 'audio' | 'video' | 'binary';
        mimeType: string;
        filename?: string;
    }>;
    meta: {
        toolName: string;
        toolCallId: string;
        /** Whether the tool execution succeeded. Always set by sanitizeToolResult(). */
        success: boolean;
    };
}

export interface InternalMessage {
    /**
     * Unique message identifier (UUID).
     * Auto-generated by ContextManager.addMessage() if not provided.
     */
    id?: string;

    /**
     * The role of the entity sending the message.
     * - 'system': System instructions or context
     * - 'user': End-user input
     * - 'assistant': LLM response
     * - 'tool': Result from a tool execution
     */
    role: 'system' | 'user' | 'assistant' | 'tool';

    /**
     * Timestamp when the message was created (Unix timestamp in milliseconds).
     * Auto-generated by ContextManager.addMessage() if not provided.
     */
    timestamp?: number;

    /**
     * The content of the message.
     * - String for system, assistant (text only), and tool messages.
     * - Array of parts for user messages (can include text, images, files, and UI resources).
     * - null if an assistant message only contains tool calls.
     */
    content: string | null | Array<TextPart | ImagePart | FilePart | UIResourcePart>;

    /**
     * Optional model reasoning text associated with an assistant response.
     * Present when the provider supports reasoning and returns a final reasoning trace.
     */
    reasoning?: string;

    /**
     * Optional token usage accounting for this assistant response.
     */
    tokenUsage?: {
        inputTokens?: number;
        outputTokens?: number;
        reasoningTokens?: number;
        totalTokens?: number;
    };

    /**
     * Optional model identifier for assistant messages.
     * Indicates which LLM model generated this response.
     */
    model?: string;

    /** Optional provider identifier for assistant messages. */
    provider?: LLMProvider;

    /**
     * Tool calls made by the assistant.
     * Only present in assistant messages when the LLM requests tool execution.
     */
    toolCalls?: Array<{
        /**
         * Unique identifier for this tool call
         */
        id: string;

        /**
         * The type of tool call (currently only 'function' is supported)
         */
        type: 'function';

        /**
         * Function call details
         */
        function: {
            /**
             * Name of the function to call
             */
            name: string;

            /**
             * Arguments for the function in JSON string format
             */
            arguments: string;
        };
    }>;

    /**
     * ID of the tool call this message is responding to.
     * Only present in tool messages.
     */
    toolCallId?: string;

    /**
     * Name of the tool that produced this result.
     * Only present in tool messages.
     */
    name?: string;

    /**
     * Whether the tool execution was successful.
     * Only present in tool messages.
     * Must be explicitly set to true or false.
     */
    success?: boolean;

    /**
     * Whether this tool call required user approval before execution.
     * Only present in tool messages.
     */
    requireApproval?: boolean;

    /**
     * The approval status for this tool call.
     * Only present in tool messages that required approval.
     */
    approvalStatus?: 'pending' | 'approved' | 'rejected';

    /**
     * Timestamp when the tool output was compacted/pruned.
     * Only present in tool messages that have been pruned.
     */
    compactedAt?: number;

    /**
     * Optional metadata for the message.
     * Used for tracking summary status, original message IDs, etc.
     */
    metadata?: Record<string, unknown>;
}
