/**
 * Error codes for scheduler operations
 */

export enum SchedulerErrorCode {
    // Configuration errors
    SCHEDULER_NOT_ENABLED = 'SCHEDULER_NOT_ENABLED',
    SCHEDULER_INVALID_CONFIG = 'SCHEDULER_INVALID_CONFIG',
    SCHEDULER_MISSING_STORAGE = 'SCHEDULER_MISSING_STORAGE',

    // Schedule validation errors
    SCHEDULE_INVALID_CRON = 'SCHEDULE_INVALID_CRON',
    SCHEDULE_INVALID_INPUT = 'SCHEDULE_INVALID_INPUT',
    SCHEDULE_LIMIT_REACHED = 'SCHEDULE_LIMIT_REACHED',

    // Schedule CRUD errors
    SCHEDULE_NOT_FOUND = 'SCHEDULE_NOT_FOUND',
    SCHEDULE_CREATE_FAILED = 'SCHEDULE_CREATE_FAILED',
    SCHEDULE_UPDATE_FAILED = 'SCHEDULE_UPDATE_FAILED',
    SCHEDULE_DELETE_FAILED = 'SCHEDULE_DELETE_FAILED',

    // Execution errors
    SCHEDULE_EXECUTION_FAILED = 'SCHEDULE_EXECUTION_FAILED',
    SCHEDULE_EXECUTION_TIMEOUT = 'SCHEDULE_EXECUTION_TIMEOUT',

    // Storage errors
    STORAGE_READ_FAILED = 'STORAGE_READ_FAILED',
    STORAGE_WRITE_FAILED = 'STORAGE_WRITE_FAILED',
}
