export const STORAGE_ERROR_CODES = [
    'storage_manager_not_initialized',
    'storage_manager_not_connected',
    'storage_dependency_not_installed',
    'storage_connection_failed',
    'storage_connection_config_missing',
    'storage_read_failed',
    'storage_write_failed',
    'storage_delete_failed',
    'storage_migration_failed',
    'storage_database_invalid_config',
    'storage_cache_invalid_config',
    'BLOB_INVALID_CONFIG',
    'BLOB_SIZE_EXCEEDED',
    'BLOB_TOTAL_SIZE_EXCEEDED',
    'BLOB_INVALID_INPUT',
    'BLOB_ENCODING_ERROR',
    'BLOB_NOT_FOUND',
    'BLOB_INVALID_REFERENCE',
    'BLOB_ACCESS_DENIED',
    'BLOB_CORRUPTED',
    'BLOB_BACKEND_NOT_CONNECTED',
    'BLOB_BACKEND_UNAVAILABLE',
    'BLOB_CLEANUP_FAILED',
    'BLOB_OPERATION_FAILED',
] as const;

export type StorageErrorCode = (typeof STORAGE_ERROR_CODES)[number];
