/**
 * Error codes for blob service operations
 */
export enum BlobErrorCode {
    // Configuration errors
    BLOB_INVALID_CONFIG = 'BLOB_INVALID_CONFIG',

    // Storage errors
    BLOB_SIZE_EXCEEDED = 'BLOB_SIZE_EXCEEDED',
    BLOB_TOTAL_SIZE_EXCEEDED = 'BLOB_TOTAL_SIZE_EXCEEDED',
    BLOB_INVALID_INPUT = 'BLOB_INVALID_INPUT',
    BLOB_ENCODING_ERROR = 'BLOB_ENCODING_ERROR',

    // Retrieval errors
    BLOB_NOT_FOUND = 'BLOB_NOT_FOUND',
    BLOB_INVALID_REFERENCE = 'BLOB_INVALID_REFERENCE',
    BLOB_ACCESS_DENIED = 'BLOB_ACCESS_DENIED',
    BLOB_CORRUPTED = 'BLOB_CORRUPTED',

    // Backend errors
    BLOB_BACKEND_NOT_CONNECTED = 'BLOB_BACKEND_NOT_CONNECTED',
    BLOB_BACKEND_UNAVAILABLE = 'BLOB_BACKEND_UNAVAILABLE',

    // Operation errors
    BLOB_CLEANUP_FAILED = 'BLOB_CLEANUP_FAILED',
    BLOB_OPERATION_FAILED = 'BLOB_OPERATION_FAILED',
}
