/**
 * Image Definition Types (bundler-only)
 *
 * The bundler consumes a `dexto.image.ts` file that declares metadata and defaults.
 * Concrete tools/storage/hooks/compaction factories are discovered from convention folders
 * and must `export const factory = ...` from their `index.ts`.
 */

import type { ImageDefaults } from '@dexto/agent-config';

/**
 * Image definition structure consumed by `@dexto/image-bundler`.
 *
 * Note: Provider factories are discovered from folders; this file is metadata + defaults only.
 */
export interface ImageDefinition {
    /** Unique name for this image (e.g., 'image-local') */
    name: string;
    /** Semantic version of this image */
    version: string;
    /** Brief description of this image's purpose */
    description: string;

    /** Target deployment environment (for documentation and validation) */
    target?: string;

    /** Runtime constraints this image requires (for validation and error messages) */
    constraints?: string[];

    /** Parent image package name to extend (optional) */
    extends?: string;

    /**
     * Default configuration values (merged into agent config; config wins).
     *
     * This must match the `AgentConfig` shape. Unknown fields will be rejected by schema validation.
     */
    defaults?: ImageDefaults;

    /**
     * Utility exports (optional).
     * Maps export name to file path (relative to image root).
     */
    utils?: Record<string, string>;

    /**
     * Selective named exports from packages (optional).
     */
    exports?: Record<string, string[]>;
}

/**
 * Metadata about a built image (generated by bundler).
 */
export interface ImageMetadata {
    /** Image name */
    name: string;
    /** Image version */
    version: string;
    /** Description */
    description: string;
    /** Target environment */
    target?: string;
    /** Runtime constraints */
    constraints: string[];
    /** Build timestamp */
    builtAt: string;
    /** Core version this image was built for */
    coreVersion: string;
    /** Base image this extends (if any) */
    extends?: string;
}
