/**
 * Orchestration Service Error Codes
 */

export enum OrchestrationErrorCode {
    // Service lifecycle errors
    SERVICE_NOT_INITIALIZED = 'ORCHESTRATION_SERVICE_NOT_INITIALIZED',
    INVALID_CONFIG = 'ORCHESTRATION_INVALID_CONFIG',

    // Todo management errors
    TODO_NOT_FOUND = 'ORCHESTRATION_TODO_NOT_FOUND',
    TODO_LIMIT_EXCEEDED = 'ORCHESTRATION_TODO_LIMIT_EXCEEDED',
    INVALID_TODO_STATUS = 'ORCHESTRATION_INVALID_TODO_STATUS',
    TODO_UPDATE_FAILED = 'ORCHESTRATION_TODO_UPDATE_FAILED',
    TODO_CREATE_FAILED = 'ORCHESTRATION_TODO_CREATE_FAILED',
    TODO_DELETE_FAILED = 'ORCHESTRATION_TODO_DELETE_FAILED',

    // Session errors
    SESSION_NOT_FOUND = 'ORCHESTRATION_SESSION_NOT_FOUND',
    SESSION_INVALID = 'ORCHESTRATION_SESSION_INVALID',

    // Database errors
    DATABASE_ERROR = 'ORCHESTRATION_DATABASE_ERROR',
    TRANSACTION_FAILED = 'ORCHESTRATION_TRANSACTION_FAILED',
}
