import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    apiSidebar: [
        'getting-started',
        {
            type: 'category',
            label: 'REST API',
            link: {
                type: 'generated-index',
                title: 'REST API',
                description: 'Explore the Dexto REST API endpoints for programmatic interaction.',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'rest',
                },
            ],
        },
        'websocket',
        {
            type: 'category',
            label: 'Dexto SDK',
            link: {
                type: 'generated-index',
                slug: 'category/typescript-sdk',
                title: 'Dexto SDK API Reference',
                description:
                    'Complete technical API reference for the Dexto SDK for TypeScript/JavaScript.',
            },
            items: [
                'dexto-agent',
                'mcp-manager',
                'prompts-manager',
                'webui-slash-commands',
                'events',
                'types',
            ],
        },
    ],
};

export default sidebars;
