import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    apiSidebar: [
        {
            type: 'doc',
            id: 'getting-started',
            label: 'Getting Started',
        },
        {
            type: 'link',
            label: 'REST API Reference',
            href: '/api/rest',
        },
        {
            type: 'doc',
            id: 'websocket',
            label: 'WebSocket API',
        },
        {
            type: 'category',
            label: 'Dexto SDK',
            link: {
                type: 'generated-index',
                title: 'Dexto SDK API Reference',
                description:
                    'Complete technical API reference for the Dexto SDK for TypeScript/JavaScript.',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'sdk',
                },
            ],
        },
    ],
};

export default sidebars;
