import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // Manual sidebar configuration for better organization and aesthetics
    tutorialSidebar: [
        {
            type: 'category',
            label: 'Getting Started',
            className: 'sidebar-icon-getting-started',
            collapsed: false,
            link: {
                type: 'generated-index',
                title: 'Getting Started',
                description: 'Quickly set up Dexto and start automating with natural language.',
            },
            items: [{ type: 'autogenerated', dirName: 'getting-started' }],
        },
        {
            type: 'category',
            label: 'Guides',
            className: 'sidebar-icon-guides',
            collapsed: false,
            link: {
                type: 'generated-index',
                title: 'Guides',
                description: 'Practical guides for using and building with Dexto.',
            },
            items: [{ type: 'autogenerated', dirName: 'guides' }],
        },
        {
            type: 'category',
            label: 'Tutorials',
            className: 'sidebar-icon-tutorials',
            collapsed: false,
            link: {
                type: 'generated-index',
                title: 'Tutorials',
                description: 'Tutorials for using Dexto',
            },
            items: [{ type: 'autogenerated', dirName: 'tutorials' }],
        },
        {
            type: 'category',
            label: 'MCP',
            className: 'sidebar-icon-mcp',
            collapsed: false,
            link: {
                type: 'generated-index',
                title: 'Model Context Protocol',
                description:
                    'Connect Dexto to MCP servers, manage tools, and expose agents over MCP.',
            },
            items: [{ type: 'autogenerated', dirName: 'mcp' }],
        },
        {
            type: 'category',
            label: 'Concepts',
            className: 'sidebar-icon-concepts',
            collapsed: false,
            link: {
                type: 'generated-index',
                title: 'Concepts',
                description: 'Core concepts for understanding Dexto.',
            },
            items: [{ type: 'autogenerated', dirName: 'concepts' }],
        },
        {
            type: 'category',
            label: 'Community',
            className: 'sidebar-icon-community',
            collapsed: false,
            link: {
                type: 'generated-index',
                title: 'Community',
                description: 'Learn how to contribute to the Dexto ecosystem.',
            },
            items: [
                {
                    type: 'link',
                    label: 'Contributing',
                    href: 'https://github.com/truffle-ai/dexto/blob/main/CONTRIBUTING.md',
                },
            ],
        },
        {
            type: 'category',
            label: 'Architecture',
            className: 'sidebar-icon-architecture',
            collapsed: false,
            link: {
                type: 'generated-index',
                title: 'Architecture',
                description: 'Technical and conceptual information about Dexto.',
            },
            items: [{ type: 'autogenerated', dirName: 'architecture' }],
        },
    ],
};

export default sidebars;
