/**
 * FileSystem Service Error Codes
 *
 * Standardized error codes for file system operations
 */

export enum FileSystemErrorCode {
    // File not found errors
    FILE_NOT_FOUND = 'FILESYSTEM_FILE_NOT_FOUND',
    DIRECTORY_NOT_FOUND = 'FILESYSTEM_DIRECTORY_NOT_FOUND',

    // Permission errors
    PERMISSION_DENIED = 'FILESYSTEM_PERMISSION_DENIED',
    PATH_NOT_ALLOWED = 'FILESYSTEM_PATH_NOT_ALLOWED',
    PATH_BLOCKED = 'FILESYSTEM_PATH_BLOCKED',

    // Validation errors
    INVALID_PATH = 'FILESYSTEM_INVALID_PATH',
    PATH_TRAVERSAL_DETECTED = 'FILESYSTEM_PATH_TRAVERSAL_DETECTED',
    INVALID_FILE_EXTENSION = 'FILESYSTEM_INVALID_FILE_EXTENSION',
    INVALID_ENCODING = 'FILESYSTEM_INVALID_ENCODING',

    // Size errors
    FILE_TOO_LARGE = 'FILESYSTEM_FILE_TOO_LARGE',
    TOO_MANY_RESULTS = 'FILESYSTEM_TOO_MANY_RESULTS',

    // Operation errors
    READ_FAILED = 'FILESYSTEM_READ_FAILED',
    WRITE_FAILED = 'FILESYSTEM_WRITE_FAILED',
    BACKUP_FAILED = 'FILESYSTEM_BACKUP_FAILED',
    EDIT_FAILED = 'FILESYSTEM_EDIT_FAILED',
    STRING_NOT_UNIQUE = 'FILESYSTEM_STRING_NOT_UNIQUE',
    STRING_NOT_FOUND = 'FILESYSTEM_STRING_NOT_FOUND',

    // Search errors
    GLOB_FAILED = 'FILESYSTEM_GLOB_FAILED',
    SEARCH_FAILED = 'FILESYSTEM_SEARCH_FAILED',
    INVALID_PATTERN = 'FILESYSTEM_INVALID_PATTERN',
    REGEX_TIMEOUT = 'FILESYSTEM_REGEX_TIMEOUT',

    // Configuration errors
    INVALID_CONFIG = 'FILESYSTEM_INVALID_CONFIG',
    SERVICE_NOT_INITIALIZED = 'FILESYSTEM_SERVICE_NOT_INITIALIZED',
}
